
packageExtensions:
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"
  "@fluentui/react-hooks@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
  "@fluentui/react@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
      "@types/react-dom":
        optional: true
      react-dom:
        optional: true
  "@fluentui/style-utilities@*":
    peerDependencies:
      "@types/react": "*"
      react: "*"
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
  "@thematic/fluent@*":
    peerDependencies:
      react-dom: "*"
      styled-components: "*"
  react-router-dom@*:
    peerDependenciesMeta:
      react-dom:
        optional: true
  styled-components@*:
    dependencies:
      react-is: ^16
    peerDependenciesMeta:
      react-dom:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
