version: '3'

services:
  frontend:
      build:
        context: .
        dockerfile: Frontend.dockerfile
      ports:
        - 3000:3000
      volumes:
        - ./:/app

  backendapi:
    build: ./python/api-backend
    environment:
      - ENABLE_CORS=http://localhost:3000
      - REDIS_URL=redis://redis:6379/0
      - STORAGE=/data
    ports:
      - 8081:8081
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
