parameters:
  name: ""
  subscription: ""
  aksClusterName: ""
  aksResourceGroup: ""
  valueFile: ""

jobs:
  - job: ${{ parameters.name }}
    steps:
      #
      # Deploy Helm Chart
      #
      - task: HelmInstaller@0
        displayName: "Install Helm 3.9.0"
        inputs:
          helmVersion: 3.9.0

      - task: HelmDeploy@0
        displayName: "Validate helm package"
        inputs:
          command: package
          chartPath: "helm"
          destination: "helm/dist"
          save: false

      - task: HelmDeploy@0
        displayName: "Deploy chart to cluster"
        inputs:
          azureSubscription: "${{ parameters.subscription }}"
          azureResourceGroup: "${{ parameters.aksResourceGroup }}"
          kubernetesCluster: "${{ parameters.aksClusterName }}"
          command: upgrade
          chartType: FilePath
          chartPath: "helm"
          releaseName: "transparency-engine"
          valueFile: "${{ parameters.valueFile }}"
          waitForExecution: false
